### ISSUE TITLE
Keycode 187 (+/=) is inconsistent across browsers

### ISSUE THREAD

**Issue by joanneong** [bernicecpz/Kumite-Scoring-Board#2]
**Describe the bug**
In the application, `+/=` is used to increment the timer by 30 seconds. This is implemented as the key code 187 in the application JavaScript. However, this key code is not consistent across browsers, [particularly Firefox](http://www.javascripter.net/faq/keycodes.htm):

<img width="461" alt="image" src="https://user-images.githubusercontent.com/24493463/66145594-c3918c00-e63d-11e9-9783-4c51b40cdfe8.png">
 
**To Reproduce**
1. Open the application in Firefox.
2. Try to increment the timer using `+/=`. No changes appear for the timer.

**Expected behavior**
The timer should have been changed according to the shortcut.

**Suggestion**
Instead of using `+/=` as the shortcut, how about something like `tab` that is consistent across the major browsers in terms of key codes? Otherwise, just including key code `61` for Firefox will include other keys for the other browsers as well. 

This would also entail changes to the keyboard layout diagram.

**Comment by bernicecpz** [comment]
After reading up and checking the keycodes, I decided to replace `+/=` with backquotes with keycode 192 which is consistent across the platforms. It is also positioned in an ascending order of the various increments in th keyboard layout diagram, i.e 30 seconds, 1 minute, 2 minute and so on for the keyboard shortcut. The keyboard layout diagram has also been updated . #5

**Comment by bernicecpz** [comment]
After reading up and checking the keycodes, I decided to replace `+/=` with backquotes with keycode 192 which is consistent across the platforms. It is also positioned in an ascending order of the various increments in th keyboard layout diagram, i.e 30 seconds, 1 minute, 2 minute and so on for the keyboard shortcut. The keyboard layout diagram has also been updated . #5
